### ISSUE TITLE
ES6 compatibility

### ISSUE THREAD

**Issue by jgautheron** [JedWatson/react-codemirror#51]
I'm trying to use `react-codemirror` in my ES6 project but it fails.

Importing it that way:
```js
import CodeMirror from 'react-codemirror';
```

Getting the following error:
```
[0] ./~/react-codemirror/src/codemirror.js
[0] Module parse failed: app/node_modules/react-codemirror/src/codemirror.js Unexpected token (76:3)
[0] You may need an appropriate loader to handle this file type.
[0] SyntaxError: Unexpected token (76:3)
...
[0]  @ ./~/react-codemirror/lib/Codemirror.js 20:42-63
```

Am I doing something wrong or is the project not compatible yet?

**Comment by hamishtaplin** [comment]
@jgautheron I'm using it with es6 no problems, seems like an issue with your babel setup to me.

**Comment by jgautheron** [comment]
I kind of figured it out, related to server side rendering. The issue is not related with `react-codemirror` so I'm closing it.

**Comment by fantasy8-me** [comment]
I encounter a similar error
```
Time: 21025ms
 Asset     Size  Chunks       Chunk Names
app.js  8.46 MB       0       main
chunk    {0} app.js (main) 3.09 MB [rendered]

ERROR in ./~/react-codemirror/src/codemirror.js
Module parse failed: /Users/me/Work/WS/sublime-master-ws/prj-reedsec/reedsec-dashboard/node_modules/react-codemirror/src/codemirror.js Unexpected token (76:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (76:3)
```

I found the problem caused by webpack loading setting, in below line
https://github.com/JedWatson/react-codemirror/blob/master/src/Codemirror.js#L17

it is expected to load 'codemirror' in 'node_module'

But if we have webpack like below, which treat 'src' as module folder too, then  'https://github.com/JedWatson/react-codemirror/blob/master/src/Codemirror.js' itself might be load and cause the error

```
  resolve: {
    modulesDirectories: [
      'src',
      'node_modules'
    ],
    extensions: ['', '.json', '.js', '.jsx']
  },
```

Remove above resolve setting can solve the problem, but can we change the src file name(Codemirror.js) to avoid conflict with the 'codemirror' module for safety

**Comment by kai23** [comment]
Have the exact same issue with webpack and ES6

**Comment by vokar97** [comment]
I had same problem on the mac os 10.11.6 (with default Journaled HFS+ case-insensitive file-system), but I've already resolved it by changing file name of src/Codemirror.js (thanks fantasy8-me). So I fully agree with fantasy8-me's advice of renaming src file to avoid conflict!

**Comment by OleksiiShevchenko** [comment]
You can change webpack config rather than rename a file https://github.com/JedWatson/react-codemirror/issues/39#issuecomment-220799966
